### ISSUE TITLE
Table of content becomes a code block.

### ISSUE THREAD

**Issue by joezhouchenye** [onlyafly/number-headings-obsidian#23] opened 2021-11-11 07:20 UTC
The auto toc adds a tab before the toc content which will result in a code block in the preview mode.

**Comment by onlyafly** [comment] 2021-12-13 10:18
@joezhouchenye I'm not able to reproduce this bug. Can you give me an example?

**Comment by joezhouchenye** [comment] 2021-12-13 12:02
Thanks for replying. After a few attempts, I have found what causes this bug. If the file has a first-level heading, the auto toc works well. However, in a file that starts from a second-level heading, the bug appears.

Without H1
![image](https://user-images.githubusercontent.com/59191277/145808308-800ee6a3-4113-4a40-aa73-54c2ccd4ab3d.png)

With H1
![image](https://user-images.githubusercontent.com/59191277/145808607-6a6ae726-984a-421e-bec7-093be0953fb3.png)

**Comment by onlyafly** [comment] 2022-06-19 08:56
Fixed in version 1.9.0

**Closed by onlyafly** 2022-06-19 08:56 UTC
Labels: bug
