### ISSUE TITLE
Numbering can destory the link

### ISSUE THREAD

**Issue by SiberiaCat00** [onlyafly/number-headings-obsidian#57] opened 2023-10-10 11:25 UTC
When I take a link to a heading and after the number of the heading is changed, the link will be destroyed
![image](https://github.com/onlyafly/number-headings-obsidian/assets/95274916/3720d5b3-56c2-491b-b7c1-9640e2c55054)

**Comment by ghost** [comment] 2023-10-13 13:46
same question

**Comment by FFSchier** [comment] 2023-11-11 21:34
Hi @onlyafly! I found this plug-in through the Obsidian community page, looking for a way to number headings. And it's really great - thank you for creating and sharing it! 

Unfortunately, this breaking of refrences to headings is a bit of a headache to me, and the only reason from refraining to fully embrace and utilize this plugin. Is there any chance you could have a look into this? 
First glance at the forums seems that it's really not as straight forward as I hoped, especially across files. 
The [Persistent Links](https://github.com/ivan-lednev/obsidian-persistent-links)-plugin seems to hook into this a bit, maybe? But that's only for cut&paste. 


A workaround for now: Use `link to blocks` instead of `headings` in the reference. Not ideal, because keeping the naming up-to-date is a manual task, but maybe it helps someone.

**Comment by onlyafly** [comment] 2023-11-12 07:51
Thanks @Glokta0, I wish there was a way to fix this, but I'm not currently sure how.

**Comment by onlyafly** [comment] 2023-11-12 07:52
Closing as duplicate of #26

**Closed as not planned** 2023-11-12 07:52 UTC
